export const data = [
  { name: "sting", index: 0 },
  { name: "purchase", index: 1 },
  { name: "flag", index: 2 },
  { name: "mistake", index: 3 },
  { name: "walk", index: 4 },
  { name: "garage", index: 5 },
  { name: "swap", index: 6 },
  { name: "adult", index: 7 },
  { name: "lounge", index: 8 },
  { name: "creek", index: 9 },
  { name: "praise", index: 10 },
  { name: "memory", index: 11 },
  { name: "squeeze", index: 12 },
  { name: "romance", index: 13 },
  { name: "secret", index: 14 },
  { name: "sudden", index: 15 },
  { name: "disagree", index: 16 },
  { name: "couch", index: 17 },
  { name: "pulse", index: 18 },
  { name: "engine", index: 19 },
  { name: "reunion", index: 20 },
  { name: "usage", index: 21 },
  { name: "fatigue", index: 22 },
  { name: "stage", index: 23 },
];

export const dataConfirm = [
  { list: ["level ", "taxi ", "leader"], index: 0 },
  { list: ["shift ", "abstract ", "chunk"], index: 3 },
  { list: ["distance ", "base ", "stable"], index: 6 },
  { list: ["erupt ", "educate ", "state"], index: 9 },
  { list: ["wife ", "zebra ", "chief"], index: 12 },
  { list: ["wonder ", "among ", "nature"], index: 15 },
];
